language: go

go:
  - 1.5
  - 1.6
  - 1.7

# services:
#   - mysql

env:
 - GOMAXPROCS=4

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/mattn/go-sqlite3

script:
  - go test -v -covermode=count -coverprofile=cover.out --tags=integration ./...

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=cover.out
